name: car_drivers
description: Car drivers API
version: 0.0.1
author: stable|kernel <iazarev@yahoo.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0
  meta: any

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0